### ISSUE TITLE
Error when callback lists are empty

### ISSUE THREAD

**Issue by JonasCir** [yandex/pgmigrate#22]
Hi, thank you for creating this tool, it's super useful!
The tool errors for the following `migrations.yml` files. A connection string is provided on the CLI in all cases.

```
callbacks:
    beforeAll:
    beforeEach:
    afterEach:
    afterAll:
```

```
Traceback (most recent call last):
  File "/usr/local/bin/pgmigrate", line 8, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.8/dist-packages/pgmigrate.py", line 829, in _main
    config = get_config(args.base_dir, args)
  File "/usr/local/lib/python3.8/dist-packages/pgmigrate.py", line 767, in get_config
    callbacks=_get_callbacks(conf.callbacks, conf.base_dir))
  File "/usr/local/lib/python3.8/dist-packages/pgmigrate.py", line 505, in _get_callbacks
    return _parse_dict_callbacks(callbacks, ret, base_dir)
  File "/usr/local/lib/python3.8/dist-packages/pgmigrate.py", line 482, in _parse_dict_callbacks
    for j in callbacks[i]:
TypeError: 'NoneType' object is not iterable

```
and for 
```
callbacks:
```
```
Traceback (most recent call last):
  File "/usr/local/bin/pgmigrate", line 8, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.8/dist-packages/pgmigrate.py", line 829, in _main
    config = get_config(args.base_dir, args)
  File "/usr/local/lib/python3.8/dist-packages/pgmigrate.py", line 767, in get_config
    callbacks=_get_callbacks(conf.callbacks, conf.base_dir))
  File "/usr/local/lib/python3.8/dist-packages/pgmigrate.py", line 506, in _get_callbacks
    return _parse_str_callbacks(callbacks, ret, base_dir)
  File "/usr/local/lib/python3.8/dist-packages/pgmigrate.py", line 457, in _parse_str_callbacks
    callbacks = callbacks.split(',')
AttributeError: 'NoneType' object has no attribute 'split'
```
If the `migrations.yml` is present, but completely empty, the error is
```
Traceback (most recent call last):
  File "/usr/local/bin/pgmigrate", line 8, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.8/dist-packages/pgmigrate.py", line 829, in _main
    config = get_config(args.base_dir, args)
  File "/usr/local/lib/python3.8/dist-packages/pgmigrate.py", line 747, in get_config
    if i in base:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by JonasCir** [comment]
I think all of this can be fixed by accounting for empty values :)

**Comment by secwall** [comment]
Hello, @JonasCir. This is definitely a bug. I've fixed it in 29208b2.
We are going to release a new version in pypi soon.
You could use install from git as a temporary workaround.

**Comment by JonasCir** [comment]
Thank you @secwall for the fast reply and fix, much appreciated :) All good, I can wait for the pypi release.

**Comment by secwall** [comment]
`1.0.6` [is out](https://pypi.org/project/yandex-pgmigrate/1.0.6/). So I'm closing this.
